config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  # get '/404', to: 'erros#error_404'
  # get '/500', to: 'erros#error_500'

  get '*unmatched_route', to: 'erros#error_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    ActiveSupport::Deprecation.silenced = true # to disablee deprications logs
    render html: "Hello"
  end

end

app/controllers/erros_controller.rb
class ErrosController < ApplicationController
  def error_404
  end

  def error_500
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def help
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
     
end

app/helpers/erros_helper.rb
module ErrosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/erros/error_404.html.erb
<% provide(:title, "404 Page Not Found") %>
<h1>
404 Page Not Found
</h1>

app/views/erros/error_500.html.erb
<% provide(:title, "500 Internal Server Error") %>
<h1>
500 Internal Server Error
</h1>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About",
'#' %></li>
<li><%= link_to "Contact", '#' %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand"><%= link_to 'Sample App', static_pages_home_path %></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <div class="nav-link"><%= link_to 'Home', static_pages_home_path %></div>
      </li>
      <li class="nav-item">
      <div class="nav-link"><%= link_to 'About', static_pages_about_path %></div>
      </li>
      <li class="nav-item">
      <div class="nav-link"><%= link_to 'Help', static_pages_help_path %></div>
      </li>
    </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
    <div class="nav-link">
  <% if user_signed_in? %>
    <%= link_to('Edit Profile', edit_user_registration_path) %>        
  <% else %>
    <%= link_to('Sign Up', new_user_registration_path) %>  
  <% end %>
  </div></li>
  <li class="nav-item"><div class="nav-link">
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  <% else %>
    <%= link_to('Login', new_user_session_path) %>  
  <% end %>
  </div></li>
  </ul>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
   <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> | Ruby on Rails Tutorial Sample App</title>
 <%= render 'layouts/rails_default' %>
  </head>
  <body>

<%= render 'layouts/header' %>

<%= render 'layouts/alerts' %>

<div class="container">
    <%= yield %>

 <%= render 'layouts/footer' %></div>
  </body>

 

</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a> is a
<a href="http://www.railstutorial.org/book">book</a> and
<a href="http://screencasts.railstutorial.org/">screencast series</a>
to teach web development with
<a href="http://rubyonrails.org/">Ruby on Rails</a>.
This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help")%>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>